inherit: [buildenv, packing-module, werror]

metaEnvironment:
   PKG_RESPONSIBLE: "System-Vernetzung"
   PKG_ARTEFACT_TYPE: "API"

depends:
  - system::tsd-common-dev
  - system::tsd-drivers-dev

  - use: []
    depends:
      - system::tsd-common-target
      - system::tsd-drivers-target

checkoutSCM:
   scm: git
   url: git@${DEFAULT_PCC_GIT_SERVER}:mib3-integration/tsd.carcom.config.api.git
   dir: tsd.carcom.config.api
   tag: mqb_sop1_eu-1.2.0
   branch: master_mqb_sop1_eu

multiPackage:
   dev:
      buildScript: |
         buildenvBuildAll
      packageScript: |
         buildenvPackageDev install
      provideDeps:
        - "*-dev"

   target:
      buildScript: |
         buildenvBuildAll
      packageScript: |
         buildenvPackageTarget
         d=$(mktemp -d)
         rsync -a --delete --exclude ".debug" ./ $d
         buildSwupModule -n "carcom-config-api" \
            -p "emmc.carcom" \
            -o "carcom:tsd-carcom-config-api " -f $d -- \
            -U "Partition=rootfs_ro"
         rm -rf $d
      provideDeps:
        - "*-target"

   doc:
      buildTools: [doxygen, dot]
      buildScript: buildenvBuildDocAll
      packageScript: buildenvPackageDoc
