environment:
   NFS:    "false" # create/updade local NFS-rootfs environment (requires root previleges)
   TFTP:   "false" # update linux kernel/DTB in a local tftp directory

   # Number of make jobs is determined by the number of available processors
   # (nproc).  If desired it can be set to a specific number, e.g. "2". See
   # classes/make.yaml for details.
   MAKE_JOBS: "nproc"

   # Run unit tests by default in build step to calculate coverage. If set to
   # "false" unit tests are only compiled but not executed.
   RUN_UNITTESTS: "true"

   # We assume building on x86_64
   AUTOCONF_BUILD: "x86_64-linux-gnu"

   # build software in secure variant
   CONFIG_SECURE: "false"
   CONFIG_VARIANTS: ".*"
   CONFIG_ANDROID: "0"
   CONFIG_HYPERVISOR: "1"
   CONFIG_INCREMENT: "0"
   CONFIG_INCREMENTAL_FILE: "OTA_FILELIST"
   CONFIG_ANDROID_SYSTEM: "1"
   CONFIG_ALLUPDATE: "1"
   CONFIG_OTA: "0"
   CONFIG_FDS: "1945"
   XTENSAD_LICENSE_FILE: '27000@10.57.9.154'
   XTENSA_LICENSE_RETRIES: '10:60'

   # Need a variable for klocwork toolchain selection. Default value for normal
   # builds is false.
   KLOCWORK: "false"
   # download artefact server: download.swi.technisat-digital
   DEFAULT_DOWNLOAD_SCM_JPCC_URL: "http://10.57.9.151:82/"
   DEFAULT_JPCC_GIT_SERVER: "10.57.9.151"
   DEFAULT_JPCC_MODIFY_GIT_SERVER: "10.57.9.150"

   DEFAULT_DOWNLOAD_SCM_URL: $(if-then-else,$(eq,${CONFIG_JPCC:-1},1),"http://10.57.9.151:82/","http://download.swi.technisat-digital/")
   DEFAULT_PCC_GIT_SERVER: $(if-then-else,$(eq,${CONFIG_JPCC:-1},1),"10.57.9.150","git.mib3.technisat-digital")

   # List of warnings that are not treated as errors
   # This should only be used in Navi Recipes
   NAVI_ALLOWED_WARNINGS: "-Wno-error=deprecated-declarations -Wno-error=unused-parameter -Wno-error=unused-function"
   # Supress specific warnings on Jenkins, to keep the statistics clean
   # This should only be used in Navi Recipes
   NAVI_SUPPRESSED_WARNINGS: "-Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-function"
   # Supress specific warnings on Jenkins, to keep the statistics clean
   # This should only be used in Recipes that compile code generated by protobuf
   PROTOBUF_SUPPRESSED_WARNINGS: "-Wno-conversion -Wno-unused-parameter -Wno-all"
   # LTO FLAG
   #LTO_ENABLE: "1"
   # FLAGS for enabling LTO Optimiation
   LTO_FLAGS: "-ffat-lto-objects -flto"


# Whitelisted environment variables that are considered build invariants and
# are always left in the environment
whitelist:
   - SSH_AGENT_PID   # ssh-agent
   - SSH_AUTH_SOCK   # ssh-agent
   - JENKINS_HOME    # Used to tell if we're running on Jenkins
   - WORKSPACE       # enables access to downloadWithCache.sh
   - COMPILER_PREFIX # used to enable ccache/icecc

# Binary archive. Upload via ssh, download via public http.
archive:
   -
      backend: http
      url: http://10.57.9.156:82/backup2/cns-artefacts/
      flags: [download]

   -
      backend: shell
      upload: "ssh upload \"mkdir -p $(dirname /var/www/backup2/cns-artefacts/${BOB_REMOTE_ARTIFACT}) \"; rsync -av --chmod=644 ${BOB_LOCAL_ARTIFACT} upload:/var/www/backup2/cns-artefacts/${BOB_REMOTE_ARTIFACT}"
      flags: [upload]

include:
#   - overrides
   - user

alias:
   navi-zr3:  "navi-zr3-dualmap"
   navi-host: "navi-host-singlemap"
   navi-map:  "navi-targetmaps-EU1/maps::ext-here-map-eu1-livecache-target"
