inherit: [buildenv, packing-module, werror]

metaEnvironment:
   PKG_RESPONSIBLE: "Connect-Smartphone Integration"

depends:
   # build dependencies
 - sal::tsd-sal-carplay-brands-dev

   # runtime dependencies
 - use: []
   depends:
    - sal::tsd-sal-carplay-brands-target

checkoutSCM:
 - scm: git
   url: git@${DEFAULT_PCC_GIT_SERVER}:mib3-ceconnect/tsd.sal.config.mib3.git
   dir: tsd.sal.config.mib3
   branch: main/svw_cns3.0_1480_dev
multiPackage:
   ? ""
   :  buildVars: [AUTOCONF_HOST]
      buildScript: buildenvBuildAll
      multiPackage:
         dev:
            packageScript: buildenvPackageDev

         target:
            packageScript: |
               buildenvPackageTarget
               d=$(mktemp -d)
               rsync -a --delete --exclude ".debug" ./ $d
               buildSwupModule -n "sal-config-mib3" \
                  -p "emmc.sal" \
                  -o "sal:tsd-sal-config-mib3 " -f $d -- \
                  -U "Partition=rootfs_ro"
               rm -rf $d

   doc:
      buildTools: [doxygen, dot]
      buildScript: buildenvBuildDocAll
      packageScript: buildenvPackageDoc


