inherit: [packing-module]
checkoutSCM:
   scm: git
   url: git@${DEFAULT_PCC_GIT_SERVER}:mib3-system/tsd.config.swdl.mib3.git
   #tag: mqb_sop1_eu-4.11.0
   branch: main/svw_cns3.0_1520_dev

depends:
  - system::tsd-config-generator

buildVars: [CONFIG_TARGET]
packageScript: |
   cp -a $1/* .
   d=$(mktemp -d)
   rsync -a --delete --exclude ".debug" ./ $d
   buildSwupModule -n "config-swdl-mib3" \
      -p "emmc.system" \
      -o "system:tsd-config-swdl-mib3 " -f $d -- \
      -U "Partition=rootfs_ro"
   rm -rf $d

multiPackage:
   # build-time configuration files of other packages, e.g. busybox
   buildcfg:
      buildScript: |
         if [[ $CONFIG_TARGET == 'swupdate' ]]; then
            rsync -a --delete $1/buildcfg/ .
         elif [[ $CONFIG_TARGET == 'swupdatemin' ]]; then
            rsync -a --delete $1/min/buildcfg/ .
         fi

# files that are put into the root file system
   target:
      privateEnvironment:
         is37W: "$(flagIsSet,${VARIANTS},SW_HMI_PROJECT,37W)"
         SW_DEVELOP: "$(flagIsSet,${VARIANTS},SW_DEV_ACCESS,1)"
         SKODA: "$(flagIsSet,${VARIANTS},SW_HMI_BRAND,sk)"

      buildVars: [is37W, SW_DEVELOP, SKODA]
      buildScript: |
         rm -rf *
         if [[ $CONFIG_TARGET == 'swupdate' ]]; then
            rsync -a --delete $1/target/ .
            if [[ "$SKODA" == "False" ]]; then
              mv tsd/volkswagen-logo.png tsd/logo.png || true
              rm -f tsd/skoda-logo.png
            else
              mv tsd/skoda-logo.png tsd/logo.png || true
              rm -f tsd/volkswagen-logo.png
            fi
            if [[ "$SW_DEVELOP" == "False" ]]; then
               mv etc/pam.d/login_secure etc/pam.d/login || true
               rm -f etc/pam.d/login_unsecure
            else
               mv etc/pam.d/login_unsecure etc/pam.d/login || true
               rm -f etc/pam.d/login_secure
            fi
         elif [[ $CONFIG_TARGET == 'swupdatemin' ]]; then
            rsync -a --delete $1/min/target/ .
            mkdir -p usr/bin
            cp $1/target/usr/bin/{formatEmmc,emmc-functions}.sh usr/bin/
         fi
         python ${BOB_DEP_PATHS['system::tsd-config-generator']}/genConf.py $1/buildcfg/cpu.conf . \
               -D37W=${is37W} -DSW_DEVELOP=${SW_DEVELOP}

